proc sort data=projectw.loans out=projectw.loansbympcode;
by mpcode;
run;
proc sort data=projectw.maturityperiod out=projectw.maturityperiodso;
by mpcode;
run;
data projectw.lonsandmaturity;
merge projectw.loansbympcode(in=loans) projectw.maturityperiodso (in= mpso);
by mpcode;
if loans and mpso;
run;
proc sort data=projectw.lonsandmaturity;
by mp_band;
run;
proc sort data=projectw.maturityperiodso;
by mp_band;
run;
data projectw.matureloans;
merge projectw.lonsandmaturity(in=lm) projectw.maturityperiodso(in=mps);
by mp_band;
if first.mp_band then;
	do;
		tapproved+approved;
	end;
if last.mp_band;
keep mp_band tapproved;
run;
proc print data=projectw.matureloans;
run;
