proc sort data=projectw.loans;
by e_emp_id;
run;
proc sort data=projectw.employee;
by e_emp_id;
run;
data projectw.emp_prfrmnc_rejectNaccept;
merge projectw.loans(in=loans) projectw.employee(in=emp);
by e_emp_id;
if loans=1 and emp=1;
retain Status;
if applied < approved then status="Accepted";
else status="Rejected";
run;
data projectw.accepted projectw.rejected;
set projectw.emp_prfrmnc_rejectNaccept;
if status="Accepted" then output projectw.accepted;
else if status="Rejected" then output projectw.rejected;
run;
proc sort data=projectw.emp_prfrmnc;
by decending perform;
run;
proc freq data=projectw.rejected ;
tables e_emp_id /nocum nopercent;
run;
