libname projectw "S:\Bank Project\Base SQL Macros\Data Sets";
*a);
proc sort data=porjectw.geography;
by g_brnch_cd;
run;
proc sort data=projectw.loans;
by g_brnch_cd;
run;
data projectw.brnchPrfrmns projectw.brnchPrfrmnsSort;
merge projectw.geography (in=geo) projectw.loans(in=loans);
by g_brnch_cd;
if first.g_brnch_cd then;
	do;
		tapproved+approved;
	end;
if last.g_brnch_cd;
keep g_brnch_cd g_country g_zone g_state G_city g_area g_branch tapproved;
output projectw.brnchPrfrmnsSort;
run;
proc sort data=projectw.brnchPrfrmnsSort;
by descending tapproved;
run;
proc print data=projectw.brnchPrfrmnsSort (obs=5);
run;
*b);
proc sort data=porjectw.geography;
by g_brnch_cd;
run;
proc sort data=projectw.loans;
by g_brnch_cd;
run;
data projectw.brnchPrfrmnsloans projectw.brnchPrfrmnsSortloans;
merge projectw.geography (in=geo) projectw.loans(in=loans);
by g_brnch_cd;
if first.g_brnch_cd then;
	do;
		tapplied+applied;
	end;
if last.g_brnch_cd;
keep g_brnch_cd g_country g_zone g_state G_city g_area g_branch tapplied;
output projectw.brnchPrfrmnsSortloans;
run;
proc sort data=projectw.brnchPrfrmnsSortloans;
by tapplied;
run;
proc print data=projectw.brnchPrfrmnsSortloans (obs=5);
run;
*c);

*d);

proc sort data=porjectw.geography;
by g_brnch_cd;
run;
proc sort data=projectw.loans;
by g_brnch_cd;
run;
data projectw.brnchPrfrmnsapproved;
merge projectw.geography (in=geo) projectw.loans(in=loans);
by g_brnch_cd;
if first.g_brnch_cd then;
	do;
		tapproved+approved;
	end;
if last.g_brnch_cd;
keep g_brnch_cd g_country g_zone g_state G_city g_area g_branch tapproved;
run;
proc sort data=projectw.brnchPrfrmnsapproved;
by tapproved;
run;
proc print data=projectw.brnchPrfrmnsapproved(obs=5);
run;
