proc sort data=projectw.loans;
by sc_chnl_cd;
run;
proc sort data=projectw.saleschannel;
by sc_chnl_cd;
run;
data projectw.loansSalesChannel;
merge projectw.loans(in=loans) projectw.saleschannel (in=salesC);
if loans=1 and salesC=1;
if first.sc_chnl_cd then;
	do;
		Tapplied+applied;
	end;
if last.sc_chnl_cd;
keep sc_chnl sc_chnl_cd Tapplied;
run;
proc sort data=projectw.loansSalesChannel;
by tapplied;
run;
proc print data=projectw.loansSalesChannel (obs=20);
run;
